services:
  db:
    image: mcr.microsoft.com/mssql/server:2025-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "${EXTERNAL_PORT}:${INTERNAL_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"$$SA_PASSWORD\" -Q \"SELECT 1\" -b -No"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  init-db:
    image: noahharriscontact/db-deployer-initializer:latest
    healthcheck:
      test: ["CMD-SHELL", "grep -q '\"status\": \"ready\"' /app/sql-scripts/status.json"]
      interval: 15s
      timeout: 5s
      retries: 20
      start_period: 30s
    depends_on:
      db:
        condition: service_healthy
    environment:
      HOST: ${HOST}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      EXTERNAL_PORT: ${EXTERNAL_PORT}
      INTERNAL_PORT: ${INTERNAL_PORT}
      DIALECT: mssql
      RESTORE_POINT_INTERVAL_MINUTES: 5
      RESTORE_POINT_RETENTION: 500

    volumes:
      - restore:/app/restore
      - sql-scripts:/app/sql-scripts

volumes:
  restore:
    driver: local
    driver_opts:
      type: none
      device: "D:/Repositories/!BACKUPS/nascar-data-scraper"
      o: bind

  sql-scripts:
    driver: local
    driver_opts:
      type: none
      device: "D:/Repositories/nascar-data-scraper/database"
      o: bind